version: 0.0
os: amazon linux
files:
  - source: /
    destination: /var/www/html
hooks:
  AfterInstall:
    - location: scripts/install_codedeploy.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/install_nginx.sh
      timeout: 300
      runas: root

